################################################################################
# kodiak.mk — Build system for Qualcomm RB3 Gen2 (QCM6490/Kodiak)
#
# Produces two independent boot artifacts:
#
#   EFI path  (default):
#     kodiak/output/efi.bin      FAT image containing uki.efi (UKI)
#
#   Boot-image path:
#     kodiak/output/tz.mbn       BL2 built by TF-A and signed with sectools
#                                (OEM TEST key); always generated by signing
#     kodiak/output/uefi.elf     FIP image (OP-TEE + U-Boot)
#
# Main targets
# ─────────────────────────────────────────────────────────────────────────────
#   all            Build OP-TEE OS, U-Boot, TF-A, Linux, Buildroot, and efi.bin
#   clean          Clean all components
#
#   efi            (Re)build the UKI FAT image from Linux + Buildroot initramfs
#   loader         Build uefi.elf (FIP) and tz.mbn (BL2 signed with sectools)
#                  via optee-os, u-boot, tfa
#
#   optee-os       Build OP-TEE OS
#   u-boot         Build U-Boot
#   tfa            Build TF-A FIP + BL2, then sign BL2 into tz.mbn with sectools
#   sectools       Download the Qualcomm signing tool (auto-invoked by sign-bl2)
#   sign-bl2       Sign the TF-A BL2 into tz.mbn (OEM TEST key)
#   linux          Build the kernel Image and DTBs
#   linux-defconfig Configure the kernel (auto-invoked by linux if needed)
#   buildroot      Build the root filesystem (via common.mk)
#   verify-blobs   Verify all pre-built blobs: bootaa64.efi (verify-bootaa64,
#                  a prereq of efi) and libqtisec.a (verify-qtiseclib — fetched
#                  if absent, then verified — a prereq of tfa)
#
#   fetch-blobs    Download QCM6490 firmware blobs directly (no Yocto build)
#   yocto          Clone meta-qcom and build the OE core-kit BSP image via kas
#   flash-loader   Flash tz.mbn + uefi.elf via QDL (checks input/ → yocto → blobs)
#   flash-efi      Flash the updated efi.bin via QDL (checks input/ → yocto → blobs)
#   flash-yocto    Flash the complete unmodified Yocto release image via QDL
#   *-clean        Per-component clean targets
#
# Configurable variables (override on the command line or in the environment)
# ─────────────────────────────────────────────────────────────────────────────
#   LINUX_DEFCONFIG       Kernel defconfig to apply (default: defconfig)
#   U-BOOT_CONFIG         U-Boot defconfig (default: qcm6490_defconfig)
#   TF_A_FLAGS            Extra flags passed to the TF-A make invocation
#   LINUX_CMDLINE         Kernel command line embedded in the UKI
#   EFI_BIN_SIZE          Size of the generated FAT32 image (default: 512M)
################################################################################

################################################################################
# Platform
################################################################################
PLATFORM            = kodiak
OPTEE_OS_PLATFORM   = qcom-kodiak

################################################################################
# Compilation settings
# All worlds are AArch64-only on this platform.
################################################################################
override COMPILE_NS_USER   := 64
override COMPILE_NS_KERNEL := 64
override COMPILE_S_USER    := 64
override COMPILE_S_KERNEL  := 64

################################################################################
# Buildroot package selection
################################################################################

# Serial console — Qualcomm MSM UART, not PL011 (overrides common.mk default)
BR2_TARGET_GENERIC_GETTY_PORT := ttyMSM0

# Networking
BR2_PACKAGE_DHCPCD  ?= y
BR2_PACKAGE_ETHTOOL ?= y
BR2_PACKAGE_XINETD  ?= y

# SSH
BR2_PACKAGE_OPENSSH           ?= y
BR2_PACKAGE_OPENSSH_SERVER    ?= y
BR2_PACKAGE_OPENSSH_KEY_UTILS ?= y

# OpenSSL CLI
BR2_PACKAGE_LIBOPENSSL_BIN ?= y

# Qualcomm FastRPC test — validates the OP-TEE PAS coprocessor reset sequence
BR2_PACKAGE_FASTRPC_EXT ?= y

# QRTR userspace, required for the DSP subsystems to finish coming up:
#   qrtr-ns   (QRTR_EXT)      — QMI name service / PD registry, launched by
#                              kodiak/overlay/etc/init.d/S40qrtr.
#   tqftpserv (TQFTPSERV_EXT) — TFTP-over-QRTR; the DSP rootPD reads its runtime
#                              from the apps rootfs over QRTR (S41tqftpserv).
# Without them the DSP protection domains never register and FastRPC stalls on
# glink intent-request timeouts.
BR2_PACKAGE_QRTR_EXT ?= y
BR2_PACKAGE_TQFTPSERV_EXT ?= y

# rmtfs — Remote Filesystem service; part of the DSP userspace stack alongside
# qrtr-ns/tqftpserv. Serves the peripherals' persistent (EFS) storage over QRTR
# (launched by S42rmtfs). It links libudev and uses /dev/disk/by-partlabel/rmtfs,
# so it needs a udev provider — switch device creation from devtmpfs-only to
# eudev (below) — and the rmtfs_mem reserved region kept by kodiak/patches/linux/
# (otherwise /dev/qcom_rmtfs_mem* are absent).
# NOTE: this completes the DSP userspace to match the vendor BSP; ADSP FastRPC
# additionally needs a 7.2.0-class kernel and still times out on the pinned
# 7.1.0-rc6 (CDSP and VIDEO pass).
BR2_PACKAGE_RMTFS_EXT ?= y
BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_EUDEV = y
# eudev needs libblkid (from util-linux) for its blkid support.
BR2_PACKAGE_UTIL_LINUX = y
BR2_PACKAGE_UTIL_LINUX_LIBBLKID = y

# Video codec validation. v4l-utils gives v4l2-ctl for capability/format
# enumeration; GStreamer gives end-to-end encode and decode pipelines through
# the venus V4L2 mem2mem codec (v4l2h264enc / v4l2h264dec), fed by
# h264parse/h265parse (videoparsers) and qtdemux (isomp4). Needs C++ (already
# on via the toolchain).
BR2_INSTALL_LIBSTDCPP                            ?= y
BR2_PACKAGE_LIBV4L                               ?= y
BR2_PACKAGE_LIBV4L_UTILS                         ?= y
BR2_PACKAGE_GSTREAMER1                           ?= y
BR2_PACKAGE_GST1_PLUGINS_BASE                    ?= y
# Base sub-plugins default off; videotestsrc feeds the encode test and
# videoconvertscale (videoconvert) handles the NV12 conversion the encoder needs.
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOTESTSRC     ?= y
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOCONVERTSCALE ?= y
BR2_PACKAGE_GST1_PLUGINS_GOOD                    ?= y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_V4L2        ?= y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_V4L2_PROBE  ?= y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_ISOMP4      ?= y
BR2_PACKAGE_GST1_PLUGINS_BAD                     ?= y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_VIDEOPARSERS ?= y

# Root filesystem — compressed CPIO for use as initramfs
BR2_TARGET_GENERIC_ISSUE     = "OP-TEE embedded distrib for $(PLATFORM)"
BR2_TARGET_ROOTFS_CPIO       = y
BR2_TARGET_ROOTFS_CPIO_GZIP  = y
BR2_PACKAGE_BUSYBOX_WATCHDOG = y

# TF-A, Linux, U-Boot and OP-TEE are built outside of Buildroot
BR2_LINUX_KERNEL              = n
# Overlay: firmware and DSP runtime only (staged by the linux-firmware target
# and fetch-blobs, see below).  No kernel-module overlay: linux-defconfig sets
# CONFIG_MODULES=n, so everything on the boot / OP-TEE / DSP path is built-in
# (=y) and there are no .ko files to stage.
BR2_ROOTFS_OVERLAY            = $(OVERLAY_DIR)
BR2_TARGET_ARM_TRUSTED_FIRMWARE = n
BR2_TARGET_OPTEE_OS           = n
BR2_TARGET_UBOOT              = n
BR2_PACKAGE_OPTEE_CLIENT      = n
BR2_PACKAGE_OPTEE_TEST        = n
BR2_PACKAGE_OPTEE_EXAMPLES    = n
BR2_PACKAGE_OPTEE_BENCHMARK   = n

################################################################################
# Paths to repositories and tooling
################################################################################
TF_A_PATH    ?= $(ROOT)/arm-trusted-firmware
U-BOOT_PATH  ?= $(ROOT)/u-boot
LINUX_PATH   ?= $(ROOT)/linux

################################################################################
# Pre-built blob integrity — files + MD5 checksums
################################################################################
# bootaa64.efi — UEFI fallback boot entry, checked in and injected into
# efi.bin by the efi target.
BOOTAA64_EFI      = $(CURDIR)/kodiak/input/bootaa64.efi
BOOTAA64_EFI_MD5  = 5bdd003de705ec4128a0e4705962fe98

# libqtisec.a — Qualcomm TrustZone security library, a required TF-A link
# input.  Not checked in: fetched on demand from the coreboot qc_blobs
# repository (raw GitHub URL so curl gets the binary directly) and
# checksum-verified before use.
LIBQTISEC_BIN     = $(CURDIR)/kodiak/security/libqtisec.a
LIBQTISEC_MD5     = 56ecb9d368a600bf89e47f8ffab11512
LIBQTISEC_URL     = https://github.com/coreboot/qc_blobs/raw/master/sc7280/qtiseclib/libqtisec.a

.PHONY: verify-blobs verify-bootaa64 verify-qtiseclib

# verify-bootaa64 — verify the checked-in UEFI fallback boot entry (efi input).
verify-bootaa64:
	@echo "$(BOOTAA64_EFI_MD5)  $(BOOTAA64_EFI)" | md5sum -c

# verify-qtiseclib — fetch libqtisec.a if absent, then checksum-verify it.
# A prerequisite of tfa: the library is fetched and validated before TF-A links.
verify-qtiseclib:
	@if [ ! -f $(LIBQTISEC_BIN) ]; then \
		echo "Downloading qtiseclib from coreboot/qc_blobs..."; \
		mkdir -p $(dir $(LIBQTISEC_BIN)); \
		curl --retry 5 -s -S -L $(LIBQTISEC_URL) -o $(LIBQTISEC_BIN) || \
			{ rm -f $(LIBQTISEC_BIN); echo "Download failed"; exit 1; }; \
	fi
	@echo "$(LIBQTISEC_MD5)  $(LIBQTISEC_BIN)" | md5sum -c

# verify-blobs — verify every pre-built blob (bootaa64.efi and libqtisec.a).
verify-blobs: verify-bootaa64 verify-qtiseclib

include common.mk
include toolchain.mk

# common.mk passes CFG_IN_TREE_EARLY_TAS to OP-TEE on the make command line,
# which turns the platform target.mk's '+= qcom_pas/...' into a no-op. Append
# the qcom_pas PAS TA here (after the include) so it is embedded as an early TA
# and advertised on the TEE bus; qcom_pas_tee (Linux) needs it to bind the PAS
# remoteprocs.
CFG_IN_TREE_EARLY_TAS += qcom_pas/cff7d191-7ca0-4784-af13-48223b9a4fbe

################################################################################
# Top-level targets
################################################################################
.PHONY: all clean

all: optee-os u-boot tfa linux buildroot efi

clean: tfa-clean optee-os-clean u-boot-clean linux-clean buildroot-clean

.PHONY: help
help:
	@echo "Qualcomm RB3 Gen2 (QCM6490/Kodiak) build system"
	@echo ""
	@echo "Output targets  (write files to kodiak/output/)"
	@echo "  make efi"
	@echo "    Intermediate: linux, buildroot"
	@echo "    Produces:     kodiak/output/efi.bin  — FAT32 image with UKI (EFI boot path)"
	@echo ""
	@echo "  make loader"
	@echo "    Intermediate: optee-os, u-boot, tfa"
	@echo "    Produces:     kodiak/output/uefi.elf — FIP image (OP-TEE + U-Boot) at 0x9fc00000"
	@echo "                  kodiak/output/tz.mbn   — BL2 signed with sectools (OEM TEST key)"
	@echo ""
	@echo "Top-level targets"
	@echo "  all            Build OP-TEE OS, U-Boot, TF-A, Linux, Buildroot, efi.bin"
	@echo "  clean          Clean all components"
	@echo ""
	@echo "Component targets"
	@echo "  optee-os       Build OP-TEE OS"
	@echo "  u-boot         Build U-Boot (\$$(U-BOOT_CONFIG))"
	@echo "  tfa            Build TF-A FIP + BL2, then sign BL2 into tz.mbn with sectools"
	@echo "  sectools       Download the Qualcomm signing tool"
	@echo "  sign-bl2       Sign the TF-A BL2 into tz.mbn (OEM TEST key)"
	@echo "  linux          Build the kernel Image + DTBs (runs linux-defconfig if .config is absent)"
	@echo "  linux-defconfig  Apply \$$(LINUX_DEFCONFIG) and the kodiak config (TEE/OP-TEE/PAS/venus, MODULES=n)"
	@echo "  buildroot      Build the root filesystem"
	@echo "  verify-blobs   Verify all pre-built blobs (bootaa64.efi + libqtisec.a; qtiseclib fetched if absent)"
	@echo "  efi            Rebuild Buildroot rootfs + kernel, build UKI, inject into kodiak/output/efi.bin"
	@echo ""
	@echo "Boot-image targets"
	@echo "  loader         Build uefi.elf (FIP) + tz.mbn (BL2 signed with sectools)"
	@echo ""
	@echo "Flash targets"
	@echo "  flash-loader   Flash tz.mbn + uefi.elf via QDL"
	@echo "                 Missing files are auto-copied from the Yocto flash directory if present,"
	@echo "                 otherwise run 'make yocto' or copy them manually to kodiak/input/"
	@echo "  flash-efi      Flash efi.bin via QDL"
	@echo "                 Same fallback logic as flash-loader for missing input files"
	@echo "  flash-yocto    Flash the complete unmodified Yocto release via QDL"
	@echo "                 Programs every rawprogram*/patch* in the Yocto deploy dir"
	@echo ""
	@echo "Firmware blob targets (alternative to 'make yocto')"
	@echo "  fetch-blobs    Download QCM6490 firmware blobs directly — no Yocto build needed"
	@echo "                 Sources: softwarecenter.qualcomm.com + codelinaro.org + qcom-ptool"
	@echo "                 Output: kodiak/blobs/  (flash targets use this as a fallback)"
	@echo "                 Lookup order: kodiak/input/ → Yocto deploy dir → kodiak/blobs/"
	@echo "  fetch-blobs-clean  Remove kodiak/blobs/"
	@echo ""
	@echo "Yocto targets"
	@echo "  yocto          Clone meta-qcom (if absent) and build OE core-kit BSP image via kas"
	@echo "                 Applies kodiak/patches/meta-qcom/ (adds fastrpc-tests to the image) before building"
	@echo "                 Output: yocto/build/tmp/deploy/images/rb3gen2-core-kit/"
	@echo "                 Copy {prog_firehose_ddr.elf,rawprogram*.xml,gpt_*.bin,patch0.xml}"
	@echo "                 to kodiak/input/ before running flash-loader or flash-efi"
	@echo "  yocto-clean    Remove the cloned meta-qcom directory"
	@echo ""
	@echo "Clean targets"
	@echo "  optee-os-clean, u-boot-clean, tfa-clean, linux-clean,"
	@echo "  buildroot-clean, efi-clean, loader-clean, yocto-clean,"
	@echo "  linux-firmware-clean"
	@echo ""
	@echo "Configurable variables (override on the command line or in the environment)"
	@echo "  LINUX_DEFCONFIG       Kernel defconfig                    (default: defconfig)"
	@echo "  U-BOOT_CONFIG         U-Boot defconfig                    (default: qcm6490_defconfig)"
	@echo "  TF_A_FLAGS            Extra flags for TF-A make           (default: PLAT=rb3gen2 SPD=opteed E=0)"
	@echo "  LINUX_CMDLINE         Kernel command line in UKI           (default: console=ttyMSM0 …)"
	@echo "  EFI_BIN_SIZE          Size of the FAT32 image             (default: 512M)"

################################################################################
# OP-TEE OS
################################################################################
OPTEE_OS_COMMON_EXTRA_FLAGS = \
	CFG_QCOM_RAMBLUR_TA_WINDOW_ID=2 \
	O=out/arm

.PHONY: optee-os optee-os-clean

optee-os: optee-os-common

optee-os-clean: optee-os-clean-common
	rm -f $(OPTEE_OS_PATH)/out/arm/core/tee-raw.bin

################################################################################
# U-Boot
#
# Configures with $(U-BOOT_CONFIG) and merges board/qualcomm/tfa-optee.config
# (CONFIG_TEE/CONFIG_OPTEE).  With CONFIG_OPTEE U-Boot advertises the OP-TEE
# node to Linux at EFI handoff.  The kodiak DT also carries the OP-TEE node
# (kodiak-el2.dtso), so OP-TEE works regardless.
################################################################################
U-BOOT_EXPORTS = CROSS_COMPILE="$(CCACHE)$(AARCH64_CROSS_COMPILE)"
U-BOOT_CONFIG  ?= qcm6490_defconfig
U-BOOT_OPTEE_FRAGMENT = board/qualcomm/tfa-optee.config

.PHONY: u-boot u-boot-clean

u-boot:
	cd $(U-BOOT_PATH) && \
		./scripts/kconfig/merge_config.sh \
			configs/qcom_defconfig \
			configs/$(U-BOOT_CONFIG) \
			$(U-BOOT_OPTEE_FRAGMENT)
	$(U-BOOT_EXPORTS) $(MAKE) -C $(U-BOOT_PATH) -j$(shell nproc)

u-boot-clean:
	$(U-BOOT_EXPORTS) $(MAKE) -C $(U-BOOT_PATH) clean

################################################################################
# ARM Trusted Firmware
#
# Build order:  optee-os → u-boot → tfa (BL32=tee-raw.bin, BL33=u-boot.bin)
#
# Generates:
#   kodiak/output/tz.mbn    BL2 built by TF-A and signed into tz.mbn with
#                           sectools (OEM TEST key).  tz.mbn is always produced
#                           by signing the freshly built BL2 — there is no
#                           checked-in pre-signed image.
#   kodiak/output/uefi.elf  FIP ELF (OP-TEE OS + U-Boot) at 0x9fc00000
################################################################################
TF_A_EXPORTS  = CROSS_COMPILE="$(AARCH64_CROSS_COMPILE)"
TF_A_FLAGS   ?= PLAT=rb3gen2 SPD=opteed E=0
FIP_LOAD_ADDR = 0x9fc00000

BL32_BIN      = $(OPTEE_OS_PATH)/out/arm/core/tee-raw.bin
BL33_BIN      = $(U-BOOT_PATH)/u-boot.bin
BL2_ELF       = $(TF_A_PATH)/build/rb3gen2/release/bl2/bl2.elf

# Sectools — Qualcomm's open-source image-signing tool, downloaded on demand and
# used to sign the TF-A-built BL2 into tz.mbn with an OEM TEST key.  Fetched from
# the public Qualcomm Software Center (no account required).
SECTOOL_MAX_RETRIES ?= 5
SECTOOL_VER   ?= 1.50
SECTOOL_ZIP   = https://softwarecenter.qualcomm.com/api/download/software/tools/Qualcomm_Security_Tools/All/1.50.0/$(SECTOOL_VER).zip

SECTOOL_DIR  ?= $(ROOT)/toolchains/sectools
# The zip unpacks to a top-level $(SECTOOL_VER)/ directory (1.50/Linux/sectools).
SECTOOL_PATH ?= $(SECTOOL_DIR)/$(SECTOOL_VER)/Linux
SECTOOL       = $(SECTOOL_PATH)/sectools
TZ_PROFILE    = $(CURDIR)/kodiak/security/kodiak_tzt_security_profile.xml

# dlsectool — download and unpack sectools, retrying on transient failures.  If
# the download cannot be completed, dlsectool exits non-zero; sign-bl2 then fails
# and the tfa target aborts (tz.mbn can only be produced by signing).
define dlsectool
	@retries=0; \
	while [ ! -x "$(SECTOOL)" ]; do \
		retries=$$((retries + 1)); \
		if [ $$retries -gt $(SECTOOL_MAX_RETRIES) ]; then \
			echo "Failed to install sectools after $(SECTOOL_MAX_RETRIES) attempts"; \
			exit 1; \
		fi; \
		mkdir -p $(SECTOOL_DIR); \
		curl --retry 5 -k -s -S -L $(SECTOOL_ZIP) -o $(SECTOOL_DIR)/tool.zip || \
			{ rm -f $(SECTOOL_DIR)/tool.zip; echo "sectools download failed, retrying..."; continue; }; \
		unzip -q -o $(SECTOOL_DIR)/tool.zip -d $(SECTOOL_DIR) && \
			chmod +x $(SECTOOL) || \
			{ rm -rf $(SECTOOL_DIR); echo "sectools archive damaged, retrying..."; continue; }; \
	done
endef

.PHONY: tfa tfa-clean sectools sign-bl2

# sectools — explicitly download the Qualcomm signing tool.
sectools:
	$(call dlsectool)

# sign-bl2 — sign the freshly built BL2 into tz.mbn (OEM TEST key).  Exits non-
# zero if sectools cannot be installed, the BL2 is missing, or signing errors.
# Invoked by the tfa target: tz.mbn is always generated by signing the BL2.
sign-bl2: sectools
	@test -f $(BL2_ELF) || { echo "sign-bl2: $(BL2_ELF) not found — run 'make tfa' first"; exit 1; }
	@mkdir -p $(CURDIR)/kodiak/output
	$(SECTOOL) secure-image $(BL2_ELF) \
		--outfile $(CURDIR)/kodiak/output/tz.mbn \
		--image-id TZ-TEE \
		--security-profile $(TZ_PROFILE) \
		--sign \
		--signing-mode TEST
	@echo "Signed BL2 -> kodiak/output/tz.mbn (OEM TEST key)"

tfa: optee-os u-boot verify-qtiseclib
	$(TF_A_EXPORTS) $(MAKE) -C $(TF_A_PATH) -j$(shell nproc) $(TF_A_FLAGS) \
		QTISECLIB_PATH=$(LIBQTISEC_BIN) \
		BL32=$(BL32_BIN) \
		BL33=$(BL33_BIN) \
		fip all
	@# tz.mbn is always produced by signing the freshly built BL2 with sectools
	@# (OEM TEST key); there is no checked-in pre-signed image to fall back to.
	$(MAKE) --no-print-directory sign-bl2
	cd $(TF_A_PATH) && $(TF_A_EXPORTS) \
		./tools/qti/generate_fip_elf.sh build/rb3gen2/release/fip.bin $(FIP_LOAD_ADDR)
	mv $(TF_A_PATH)/fip.elf $(CURDIR)/kodiak/output/uefi.elf

tfa-clean:
	$(TF_A_EXPORTS) $(MAKE) -C $(TF_A_PATH) $(TF_A_FLAGS) clean

################################################################################
# Linux kernel patches
#
# Patches in kodiak/patches/linux/ are applied to the kernel source tree once,
# tracked by a stamp file outside LINUX_PATH so mrproper cannot remove it.
# Run linux-patch-clean to reverse all patches (e.g. before a fresh checkout).
################################################################################
LINUX_PATCH_DIR   = $(CURDIR)/kodiak/patches/linux
LINUX_PATCH_STAMP = $(CURDIR)/kodiak/.linux-patches-applied

.PHONY: linux-patch linux-patch-clean

linux-patch:
	@if [ ! -f $(LINUX_PATCH_STAMP) ]; then \
		for p in $(sort $(wildcard $(LINUX_PATCH_DIR)/*.patch)); do \
			echo "Applying $$p ..."; \
			git -C $(LINUX_PATH) apply "$$p" || exit 1; \
		done; \
		touch $(LINUX_PATCH_STAMP); \
	fi

linux-patch-clean:
	@if [ -f $(LINUX_PATCH_STAMP) ]; then \
		for p in $$(ls -r $(LINUX_PATCH_DIR)/*.patch 2>/dev/null); do \
			echo "Reverting $$p ..."; \
			git -C $(LINUX_PATH) apply -R "$$p" || true; \
		done; \
		rm -f $(LINUX_PATCH_STAMP); \
	fi

################################################################################
# Linux kernel
#
# linux-defconfig applies $(LINUX_DEFCONFIG) and enables EFI_ZBOOT (required
# for the UKI stub).  It is called automatically by linux if .config is absent.
#
# All drivers on the boot / OP-TEE / DSP bring-up path must be built-in (=y),
# not modules: the rootfs is a RAM initramfs embedded in the UKI and this build
# configures no module-autoload mechanism (no mdev/udev MODALIAS coldplug), so
# loadable modules would never be loaded at runtime.  linux-defconfig therefore
# disables CONFIG_MODULES, which also forces hidden 'default m' drivers such as
# QCOM_PAS_TEE and QCOM_Q6V5_PAS built-in — required for the PAS remoteprocs
# (ADSP/CDSP/VIDEO) to probe, as they cannot wait on a late-loaded module.
# If a driver is ever needed, add it to the '-e' list here.
#
# Video: the kodiak video-codec@aa00000 node is "qcom,sc7280-venus", which BOTH
# the venus and the iris drivers match.  With CONFIG_MODULES=n both would be
# built-in and the bind is registration-order roulette, so pin the codec to the
# venus driver (-e VIDEO_QCOM_VENUS -d VIDEO_QCOM_IRIS) to avoid the collision.
#
# Generates:
#   linux/arch/arm64/boot/Image
################################################################################
LINUX_EXPORTS    = ARCH=arm64 CROSS_COMPILE="$(CCACHE)$(AARCH64_CROSS_COMPILE)"
LINUX_DEFCONFIG ?= defconfig

.PHONY: linux-defconfig linux linux-clean

linux-defconfig:
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) mrproper
	$(MAKE) linux-patch
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) $(LINUX_DEFCONFIG)
	$(LINUX_EXPORTS) $(LINUX_PATH)/scripts/config --file $(LINUX_PATH)/.config \
		-e TEE \
		-e OPTEE \
		-e DEVTMPFS \
		-e EFI_BOOT \
		-e EFI_ZBOOT \
		-e QCOM_WDT \
		-e QCOM_FASTRPC \
		-e REMOTEPROC \
		-e QCOM_Q6V5_PAS \
		-e QCOM_PAS \
		-e QCOM_PAS_TEE \
		-e RPMSG \
		-e RPMSG_QCOM_GLINK \
		-e RPMSG_QCOM_GLINK_SMEM \
		-e QCOM_SMEM \
		-e QCOM_SMP2P \
		-e QCOM_SMSM \
		-e QCOM_AOSS_QMP \
		-e QCOM_RPMHPD \
		-e QCOM_COMMAND_DB \
		-e QCOM_SCM \
		-e QRTR \
		-e QRTR_SMD \
		-e CMA \
		-e DMA_CMA \
		-e DMABUF_HEAPS \
		-e DMABUF_HEAPS_SYSTEM \
		-e DMABUF_HEAPS_CMA \
		-e VIDEO_QCOM_VENUS \
		-d VIDEO_QCOM_IRIS \
		-d QCOMTEE \
		-d MODULES
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) olddefconfig

linux: linux-patch
	@if [ ! -f $(LINUX_PATH)/.config ]; then $(MAKE) linux-defconfig; fi
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) -j$(shell nproc) Image
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) -j1 dtbs

linux-clean: linux-patch-clean
	$(LINUX_EXPORTS) $(MAKE) -C $(LINUX_PATH) clean

################################################################################
# UKI — Unified Kernel Image (efi.bin)
#
# Bundles the kernel, DTB, initramfs, and command line into a single EFI
# binary using ukify, then builds a fresh FAT32 image containing:
#   EFI/BOOT/bootaa64.efi   UEFI fallback boot entry (from kodiak/input/)
#   EFI/Linux/uki.efi       Unified Kernel Image
#
# Host dependencies:
#   apt install systemd-boot-efi systemd-ukify mtools dosfstools
#
# Generates:
#   kodiak/output/efi.bin   FAT32 image (512 MiB)
################################################################################
LINUX_IMAGE   = $(LINUX_PATH)/arch/arm64/boot/Image
LINUX_DTB     = $(LINUX_PATH)/arch/arm64/boot/dts/qcom/qcs6490-rb3gen2-el2.dtb
BR_INITRAMFS  = $(ROOT)/out-br/images/rootfs.cpio.gz
EFI_BIN_SIZE  = 512M

LINUX_CMDLINE ?= \
	console=ttyMSM0,115200 \
	qcom_scm.download_mode=1 \
	earlycon

.PHONY: efi efi-clean

efi: linux buildroot verify-bootaa64 linux-firmware
	ukify build \
		--linux=$(LINUX_IMAGE) \
		--initrd=$(BR_INITRAMFS) \
		--cmdline='$(LINUX_CMDLINE)' \
		--efi-arch=aa64 \
		--stub=$(CURDIR)/kodiak/ukify/linuxaa64.efi.stub \
		--os-release=@/etc/os-release \
		--devicetree=$(LINUX_DTB) \
		--output=$(LINUX_PATH)/uki.efi
	truncate -s $(EFI_BIN_SIZE) $(CURDIR)/kodiak/output/efi.bin
	mkfs.fat -F 32 -S 4096 $(CURDIR)/kodiak/output/efi.bin
	mmd -i $(CURDIR)/kodiak/output/efi.bin ::/EFI
	mmd -i $(CURDIR)/kodiak/output/efi.bin ::/EFI/BOOT
	mmd -i $(CURDIR)/kodiak/output/efi.bin ::/EFI/Linux
	mcopy -i $(CURDIR)/kodiak/output/efi.bin $(BOOTAA64_EFI) ::/EFI/BOOT/bootaa64.efi
	mcopy -i $(CURDIR)/kodiak/output/efi.bin $(LINUX_PATH)/uki.efi ::/EFI/Linux/uki.efi

efi-clean:
	rm -f $(LINUX_PATH)/uki.efi $(CURDIR)/kodiak/output/efi.bin

################################################################################
# Loader image (tz.mbn + uefi.elf)
#
# Builds the FIP (uefi.elf) via optee-os → u-boot → tfa.  The tfa target builds
# the BL2 and signs it into tz.mbn with sectools (OEM TEST key); tz.mbn is always
# produced by signing.
################################################################################
.PHONY: loader loader-clean

loader: optee-os u-boot tfa

loader-clean: tfa-clean optee-os-clean u-boot-clean
	rm -f kodiak/output/tz.mbn kodiak/output/uefi.elf

################################################################################
# Flash helpers
#
# Both targets expect their input files to be present in kodiak/input/.
# These files are produced by the Yocto build (make yocto) and must be copied
# from the deploy directory before flashing:
#
#   cp $(YOCTO_DEPLOY)/{prog_firehose_ddr.elf,rawprogram*.xml,\
#      gpt_main0.bin,gpt_backup0.bin,patch0.xml} kodiak/input/
#
#   flash-loader   Flashes the full loader image (tz.mbn + uefi.elf) via QDL.
#                  Requires kodiak/output/{tz.mbn,uefi.elf} — run 'make loader'
#                  first; the target errors if they are absent.
#
#   flash-efi      Flashes only the EFI partition (efi.bin / UKI) via QDL.
#                  Requires kodiak/output/efi.bin — run 'make efi' first; the
#                  target errors if it is absent.  Kernel-only update, without
#                  reflashing the loader.  rawprogram0-only-kernel.xml is
#                  generated from rawprogram0.xml (Yocto deploy) by keeping only
#                  the efi partition entry.
################################################################################
.PHONY: flash-loader flash-efi

flash-loader:
	@if [ ! -f "$(CURDIR)/kodiak/output/tz.mbn" ] || \
	    [ ! -f "$(CURDIR)/kodiak/output/uefi.elf" ]; then \
		echo "ERROR: kodiak/output/tz.mbn and/or kodiak/output/uefi.elf not found"; \
		echo "       Run 'make loader' first to build the boot chain."; \
		exit 1; \
	fi
	@for f in prog_firehose_ddr.elf rawprogram4.xml rawprogram1.xml rawprogram2.xml \
	           aop.mbn cpucp.elf devcfg.mbn hypvm.mbn imagefv.elf \
	           multi_image.mbn qupv3fw.elf shrm.elf tools.fv uefi_sec.mbn \
	           XblRamdump.elf zeros_33sectors.bin \
	           gpt_main1.bin gpt_backup1.bin gpt_main2.bin gpt_backup2.bin \
	           gpt_main4.bin gpt_backup4.bin \
	           xbl.elf xbl_config.elf; do \
		if [ ! -f "$(CURDIR)/kodiak/input/$$f" ]; then \
			if [ -f "$(YOCTO_FLASH)/$$f" ]; then \
				echo "Copying $$f from Yocto flash directory..."; \
				cp "$(YOCTO_FLASH)/$$f" "$(CURDIR)/kodiak/input/$$f"; \
			elif [ -f "$(BLOBS_DIR)/$$f" ]; then \
				echo "Copying $$f from blobs directory..."; \
				cp "$(BLOBS_DIR)/$$f" "$(CURDIR)/kodiak/input/$$f"; \
			else \
				echo "ERROR: $$f not found in kodiak/input/, $(YOCTO_FLASH), or $(BLOBS_DIR)"; \
				echo "       Run 'make fetch-blobs' or 'make yocto', or copy it manually to kodiak/input/"; \
				exit 1; \
			fi; \
		fi; \
	done
	cp $(CURDIR)/kodiak/input/prog_firehose_ddr.elf \
	   $(CURDIR)/kodiak/input/rawprogram4.xml \
	   $(CURDIR)/kodiak/input/rawprogram1.xml \
	   $(CURDIR)/kodiak/input/rawprogram2.xml \
	   $(CURDIR)/kodiak/input/aop.mbn \
	   $(CURDIR)/kodiak/input/cpucp.elf \
	   $(CURDIR)/kodiak/input/devcfg.mbn \
	   $(CURDIR)/kodiak/input/hypvm.mbn \
	   $(CURDIR)/kodiak/input/imagefv.elf \
	   $(CURDIR)/kodiak/input/multi_image.mbn \
	   $(CURDIR)/kodiak/input/qupv3fw.elf \
	   $(CURDIR)/kodiak/input/shrm.elf \
	   $(CURDIR)/kodiak/input/tools.fv \
	   $(CURDIR)/kodiak/input/uefi_sec.mbn \
	   $(CURDIR)/kodiak/input/XblRamdump.elf \
	   $(CURDIR)/kodiak/input/zeros_33sectors.bin \
	   $(CURDIR)/kodiak/input/gpt_main1.bin \
	   $(CURDIR)/kodiak/input/gpt_backup1.bin \
	   $(CURDIR)/kodiak/input/gpt_main2.bin \
	   $(CURDIR)/kodiak/input/gpt_backup2.bin \
	   $(CURDIR)/kodiak/input/gpt_main4.bin \
	   $(CURDIR)/kodiak/input/gpt_backup4.bin \
	   $(CURDIR)/kodiak/input/xbl.elf \
	   $(CURDIR)/kodiak/input/xbl_config.elf \
	   $(CURDIR)/kodiak/output/
	@# The DTB is embedded in uki.efi, so drop the dtb.bin partition entries;
	@# otherwise qdl aborts trying to open dtb.bin. fetch-blobs strips these from
	@# its own rawprogram4.xml, but a Yocto deploy's copy still carries them.
	@sed -i '/filename="dtb\.bin"/d' $(CURDIR)/kodiak/output/rawprogram4.xml
	cd $(CURDIR)/kodiak/output && \
		qdl --debug prog_firehose_ddr.elf rawprogram4.xml rawprogram1.xml rawprogram2.xml

flash-efi:
	@if [ ! -f "$(CURDIR)/kodiak/output/efi.bin" ]; then \
		echo "ERROR: kodiak/output/efi.bin not found"; \
		echo "       Run 'make efi' first to build the UKI image."; \
		exit 1; \
	fi
	@for f in prog_firehose_ddr.elf rawprogram0.xml gpt_main0.bin gpt_backup0.bin patch0.xml; do \
		if [ ! -f "$(CURDIR)/kodiak/input/$$f" ]; then \
			if [ -f "$(YOCTO_FLASH)/$$f" ]; then \
				echo "Copying $$f from Yocto flash directory..."; \
				cp "$(YOCTO_FLASH)/$$f" "$(CURDIR)/kodiak/input/$$f"; \
			elif [ -f "$(BLOBS_DIR)/$$f" ]; then \
				echo "Copying $$f from blobs directory..."; \
				cp "$(BLOBS_DIR)/$$f" "$(CURDIR)/kodiak/input/$$f"; \
			else \
				echo "ERROR: $$f not found in kodiak/input/, $(YOCTO_FLASH), or $(BLOBS_DIR)"; \
				echo "       Run 'make fetch-blobs' or 'make yocto', or copy it manually to kodiak/input/"; \
				exit 1; \
			fi; \
		fi; \
	done
	@if [ ! -f "$(CURDIR)/kodiak/input/rawprogram0-only-kernel.xml" ]; then \
		echo "Generating rawprogram0-only-kernel.xml (efi partition only)..."; \
		{ printf '<?xml version="1.0" ?>\n<data>\n'; \
		  grep 'filename="efi.bin"' "$(CURDIR)/kodiak/input/rawprogram0.xml"; \
		  printf '</data>\n'; } > "$(CURDIR)/kodiak/input/rawprogram0-only-kernel.xml"; \
	fi
	cp $(CURDIR)/kodiak/input/prog_firehose_ddr.elf \
	   $(CURDIR)/kodiak/input/rawprogram0-only-kernel.xml \
	   $(CURDIR)/kodiak/input/gpt_main0.bin \
	   $(CURDIR)/kodiak/input/gpt_backup0.bin \
	   $(CURDIR)/kodiak/input/patch0.xml \
	   $(CURDIR)/kodiak/output/
	cd $(CURDIR)/kodiak/output && \
		qdl --debug prog_firehose_ddr.elf rawprogram0-only-kernel.xml patch0.xml

################################################################################
# fetch-blobs — Download QCM6490 firmware blobs directly (no Yocto build)
#
# Replicates what 'make yocto' downloads, without running the full OE build.
# All artifacts are publicly accessible — no Qualcomm account required.
#
# Sources:
#   softwarecenter.qualcomm.com  — boot binaries zip (XBL, AOP, firehose, …)
#   artifacts.codelinaro.org     — CDT (Customer Device Tree) blob
#   github.com/qualcomm-linux/qcom-ptool — GPT tables + rawprogram XMLs
#     (these are pre-generated files committed to the repo's platforms/ tree;
#      no Python tool invocation is needed)
#
# Output: kodiak/blobs/ — flat directory, same file names as YOCTO_FLASH.
# The flash targets check this directory as a fallback when a file is absent
# from kodiak/input/ and the Yocto deploy directory does not exist.
################################################################################
BLOBS_VERSION  = 00142
BLOBS_DIR      = $(CURDIR)/kodiak/blobs
BLOBS_STAMP    = $(BLOBS_DIR)/.fetch-complete

BOOTBIN_BASE   = https://softwarecenter.qualcomm.com/nexus/generic/product/chip/tech-package/QCM6490_bootbinaries.1.0/qcm6490_bootbinaries.1.0-test-device-public/$(BLOBS_VERSION)
BOOTBIN_URL    = $(BOOTBIN_BASE)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip
BOOTBIN_SHA256 = 22e45047b3349a1611d27167616dd04f08e8351120ac121f6921b47b9f709216

# Immutable companion archive — cpucp.elf is not in the main bootbinaries zip;
# it ships in this separate "immutable" archive, the same split meta-qcom's
# firmware-qcom-boot-qcs6490 recipe fetches (main zip +
# QCM6490_bootbinaries_immutable zip, both deployed together).
BOOTBIN_IMM_URL    = $(BOOTBIN_BASE)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip
BOOTBIN_IMM_SHA256 = a5f48c1646eb640377b66fa13064f2efe6f667e60f714b0e06c34dc66b7c94fb

CDT_URL        = https://artifacts.codelinaro.org/artifactory/codelinaro-le/Qualcomm_Linux/QCS6490/cdt/rb3gen2-core-kit.zip
CDT_SHA256     = 0fe1c0b4050cf54203203812b2c1f0d9698823d8defc8b6516414a4e5e0c557e
CDT_FILE       = cdt_core_kit.bin

PTOOL_REPO     = https://github.com/qualcomm-linux/qcom-ptool.git
PTOOL_DIR      = $(BLOBS_DIR)/qcom-ptool
PTOOL_PLATFORM = qcs6490-rb3gen2

# DSP firmware staged into a buildroot overlay, following the meta-qcom layout.
# The RB3Gen2 SoC firmware namespace is qcm6490 (not qcs6490).  Two distinct
# sets are needed for the FastRPC/PAS validation:
#
#   1. Remoteproc images (cdsp.mbn/adsp.mbn): loaded by the kernel from
#      /lib/firmware/qcom/qcm6490/ — this load is what triggers the OP-TEE PAS
#      authenticate/reset path.  Upstream linux-firmware ships these as flat
#      files under qcom/qcm6490/, so we sparse-check out that dir and copy the
#      *.mbn/*.jsn.  NOTE: the mainline RB3Gen2 DTS firmware-name points at
#      qcom/qcs6490/ (which carries no flat cdsp.mbn), so kodiak-el2.dtso
#      overrides remoteproc_{adsp,cdsp} firmware-name to qcom/qcm6490/.
#
#   2. DSP runtime (fastrpc_shell* + skels): the PD runtime FastRPC pushes to
#      the DSP, plus a conf.d yaml mapping the DT model -> DSP_LIBRARY_PATH.
#      Sourced from linux-msm/dsp-binaries and installed (pruned to this board)
#      to /usr/share/qcom/qcm6490/Thundercomm/RB3gen2/dsp/ + conf.d.
FW_REPO        = https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
# Pin linux-firmware to the same dated release as the DSP runtime (DSP_TAG): the
# remoteproc images (adsp.mbn/cdsp.mbn) and the DSP runtime (fastrpc_shell +
# skels from dsp-binaries) are a matched set and must come from the same release,
# or FastRPC fails.  linux-firmware tags this release 20260519, matching DSP_TAG.
FW_SRCREV      = 20260519
FW_SOC         = qcom/qcm6490
# AudioReach ADSP topology.  RB3Gen2's ADSP is an AudioReach subsystem whose
# audio side (qcom-apm/gprsvc) loads qcom/qcs6490/QCS6490-RB3Gen2-tplg.bin — the
# board audio namespace is qcs6490, unlike the remoteproc images (overridden to
# qcm6490 by kodiak-el2.dtso).  Stage the flat qcs6490 audioreach files (the tplg).
FW_SOC_AUDIO   = qcom/qcs6490
# Video-codec firmware.  The video-codec@aa00000 node is "qcom,sc7280-venus" and
# we build the venus driver (iris disabled, see linux-defconfig), which loads the
# fixed path qcom/vpu-2.0/venus.mbn.  Upstream linux-firmware provides that path
# only as a WHENCE symlink (-> ../vpu/vpu20_p1.mbn), with the real blobs under the
# flat qcom/vpu/ dir, so we stage qcom/vpu and recreate the symlink (a plain cp
# does not process WHENCE).
FW_VPU         = qcom/vpu
FW_CLONE_DIR   = $(BLOBS_DIR)/linux-firmware
DSP_REPO       = https://github.com/linux-msm/dsp-binaries.git
DSP_TAG        = 20260519
DSP_CLONE_DIR  = $(BLOBS_DIR)/dsp-binaries
DSP_BOARD      = RB3gen2
OVERLAY_DIR    = $(CURDIR)/kodiak/overlay
FW_DEST_DIR    = $(OVERLAY_DIR)/lib/firmware/$(FW_SOC)
FW_VPU_DEST    = $(OVERLAY_DIR)/lib/firmware/$(FW_VPU)
FW_AUDIO_DEST  = $(OVERLAY_DIR)/lib/firmware/$(FW_SOC_AUDIO)
DSP_SHARE_DIR  = $(OVERLAY_DIR)/usr/share/qcom

.PHONY: fetch-blobs fetch-blobs-clean

# Ensure the overlay directory exists so the buildroot rootfs assembly never
# fails on a missing BR2_ROOTFS_OVERLAY entry when firmware has not been fetched.
$(OVERLAY_DIR):
	@mkdir -p $(OVERLAY_DIR)

buildroot: linux-firmware | $(OVERLAY_DIR)

# linux-firmware — stage upstream linux-firmware into the buildroot overlay:
#   /lib/firmware/$(FW_SOC)        — per-SoC DSP/remoteproc images + jsn
#   /lib/firmware/$(FW_SOC_AUDIO)  — AudioReach ADSP topology (tplg)
#   /lib/firmware/$(FW_VPU)        — venus video-codec firmware (vpu20_p1*.mbn)
# Standalone target, independent of fetch-blobs; 'buildroot' (and hence 'efi')
# depends on it so the firmware is baked into the rootfs/UKI regardless of when
# (or whether) fetch-blobs runs.  Pinned to FW_SRCREV.
.PHONY: linux-firmware linux-firmware-clean
linux-firmware: | $(OVERLAY_DIR)
	@mkdir -p $(BLOBS_DIR)
	@if [ ! -d $(FW_CLONE_DIR)/.git ]; then \
		echo "Cloning linux-firmware (sparse: $(FW_SOC) $(FW_SOC_AUDIO) $(FW_VPU))..."; \
		git clone --filter=blob:none --sparse $(FW_REPO) $(FW_CLONE_DIR); \
	fi
	@# Select the DSP, AudioReach and video-codec dirs. Run unconditionally so a
	@# pre-existing clone picks up any newly added dir; sparse-checkout is idempotent.
	@git -C $(FW_CLONE_DIR) sparse-checkout set $(FW_SOC) $(FW_SOC_AUDIO) $(FW_VPU)
	@# Pin to FW_SRCREV (fetch it if the local clone does not have it yet).
	@git -C $(FW_CLONE_DIR) checkout -q $(FW_SRCREV) 2>/dev/null || \
	 { git -C $(FW_CLONE_DIR) fetch -q --unshallow origin 2>/dev/null || \
	   git -C $(FW_CLONE_DIR) fetch -q origin; \
	   git -C $(FW_CLONE_DIR) checkout -q $(FW_SRCREV); }
	@mkdir -p $(FW_DEST_DIR)
	@cp -a $(FW_CLONE_DIR)/$(FW_SOC)/*.mbn $(FW_CLONE_DIR)/$(FW_SOC)/*.jsn \
	       $(FW_CLONE_DIR)/$(FW_SOC)/*.elf $(FW_DEST_DIR)/
	@# AudioReach ADSP topology (flat qcom/qcs6490/*.bin, e.g. the RB3Gen2 tplg).
	@# Only the flat files — not the per-board subdirs (other boards' large mbns).
	@mkdir -p $(FW_AUDIO_DEST)
	@cp -a $(FW_CLONE_DIR)/$(FW_SOC_AUDIO)/*.bin $(FW_AUDIO_DEST)/ 2>/dev/null || true
	@# Video-codec firmware (flat qcom/vpu/ path; vpu20_p1*.mbn).
	@mkdir -p $(FW_VPU_DEST)
	@cp -a $(FW_CLONE_DIR)/$(FW_VPU)/. $(FW_VPU_DEST)/
	@# venus driver loads the fixed path qcom/vpu-2.0/venus.mbn; recreate the
	@# upstream WHENCE symlink (-> ../vpu/vpu20_p1.mbn) that cp does not carry.
	@mkdir -p $(OVERLAY_DIR)/lib/firmware/qcom/vpu-2.0
	@ln -sfn ../vpu/vpu20_p1.mbn $(OVERLAY_DIR)/lib/firmware/qcom/vpu-2.0/venus.mbn
	@echo "linux-firmware staged in $(FW_DEST_DIR)/ and $(FW_VPU_DEST)/ (+ vpu-2.0/venus.mbn, pinned $(FW_SRCREV))"

# linux-firmware-clean — remove the cloned linux-firmware repo and the firmware
# staged into the buildroot overlay (per-SoC DSP, AudioReach, and venus dirs).
linux-firmware-clean:
	rm -rf $(FW_CLONE_DIR) $(FW_DEST_DIR) $(FW_AUDIO_DEST) $(FW_VPU_DEST) $(OVERLAY_DIR)/lib/firmware/qcom/vpu-2.0

fetch-blobs: $(BLOBS_STAMP)

$(BLOBS_STAMP):
	@mkdir -p $(BLOBS_DIR)
	@# ── Boot binaries ─────────────────────────────────────────────────────────
	@# Firmware ELFs/MBNs/FVs — excludes gpt/zeros (from ptool) and
	@# uefi.elf/tz.mbn (replaced by our own build artifacts).
	@if [ ! -f $(BLOBS_DIR)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip ]; then \
		echo "Downloading QCM6490 boot binaries..."; \
		curl --retry 5 -s -S -L $(BOOTBIN_URL) \
			-o $(BLOBS_DIR)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip || \
			{ rm -f $(BLOBS_DIR)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip; exit 1; }; \
	fi
	@echo "$(BOOTBIN_SHA256)  $(BLOBS_DIR)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip" | sha256sum -c
	@unzip -q -o $(BLOBS_DIR)/QCM6490_bootbinaries_$(BLOBS_VERSION).zip \
		-d $(BLOBS_DIR)/bootbinaries
	@# Immutable companion archive (carries cpucp.elf).
	@if [ ! -f $(BLOBS_DIR)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip ]; then \
		echo "Downloading QCM6490 immutable boot binaries..."; \
		curl --retry 5 -s -S -L $(BOOTBIN_IMM_URL) \
			-o $(BLOBS_DIR)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip || \
			{ rm -f $(BLOBS_DIR)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip; exit 1; }; \
	fi
	@echo "$(BOOTBIN_IMM_SHA256)  $(BLOBS_DIR)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip" | sha256sum -c
	@unzip -q -o $(BLOBS_DIR)/QCM6490_bootbinaries_immutable_$(BLOBS_VERSION).zip \
		-d $(BLOBS_DIR)/bootbinaries
	@find $(BLOBS_DIR)/bootbinaries -maxdepth 2 \
		\( -name '*.elf' -o -name '*.mbn' -o -name '*.fv' -o -name '*.bin' \
		   -o -name '*.melf' -o -name '*.lzma' -o -name '*.xz' \) \
		! -name 'gpt_*.bin' ! -name 'zeros_*.bin' \
		! -name 'uefi.elf'  ! -name 'tz.mbn' \
		-exec cp -n {} $(BLOBS_DIR)/ \;
	@# ── CDT blob only ─────────────────────────────────────────────────────────
	@# The CDT zip also contains rawprogram3/gpt3/firehose, but those are NOT
	@# used by Yocto — only the cdt*.bin is extracted.  GPT and rawprogram files
	@# for all LUNs (including LUN3) come from qcom-ptool below.
	@if [ ! -f $(BLOBS_DIR)/rb3gen2-core-kit.zip ]; then \
		echo "Downloading CDT (rb3gen2-core-kit)..."; \
		curl --retry 5 -s -S -L $(CDT_URL) \
			-o $(BLOBS_DIR)/rb3gen2-core-kit.zip || \
			{ rm -f $(BLOBS_DIR)/rb3gen2-core-kit.zip; exit 1; }; \
	fi
	@echo "$(CDT_SHA256)  $(BLOBS_DIR)/rb3gen2-core-kit.zip" | sha256sum -c
	@unzip -q -o $(BLOBS_DIR)/rb3gen2-core-kit.zip \
		$(CDT_FILE) -d $(BLOBS_DIR)/cdt
	@cp $(BLOBS_DIR)/cdt/$(CDT_FILE) $(BLOBS_DIR)/cdt.bin
	@# ── Partition tables: GPT bins + rawprogram XMLs via qcom-ptool ───────────
	@# qcom-ptool has no pre-generated files — partitions.conf must be processed
	@# with gen_partition (conf→XML) then ptool (XML→GPT bins + rawprogram XMLs).
	@if [ ! -d $(PTOOL_DIR) ]; then \
		echo "Cloning qcom-ptool..."; \
		git clone --depth=1 $(PTOOL_REPO) $(PTOOL_DIR); \
	fi
	@if [ ! -x $(PTOOL_DIR)/.venv/bin/qcom-ptool ]; then \
		echo "Installing qcom-ptool into venv..."; \
		python3 -m venv $(PTOOL_DIR)/.venv; \
		$(PTOOL_DIR)/.venv/bin/pip install -q $(PTOOL_DIR); \
	fi
	@PTOOL=$(PTOOL_DIR)/.venv/bin/qcom-ptool; \
	PLAT_DIR=$(PTOOL_DIR)/platforms/$(PTOOL_PLATFORM)/ufs; \
	if [ ! -d "$$PLAT_DIR" ]; then \
		echo "ERROR: platform '$(PTOOL_PLATFORM)/ufs' not found in qcom-ptool repo"; \
		echo "       Available: $$(ls $(PTOOL_DIR)/platforms/)"; \
		exit 1; \
	fi; \
	$$PTOOL gen_partition -i "$$PLAT_DIR/partitions.conf" -o "$$PLAT_DIR/partitions.xml"; \
	(cd "$$PLAT_DIR" && $$PTOOL ptool -x partitions.xml); \
	find "$$PLAT_DIR" \
		\( -name 'gpt_*.bin' -o -name 'rawprogram*.xml' \
		   -o -name 'patch*.xml' -o -name 'zeros_*.bin' \) \
		-exec cp -f {} $(BLOBS_DIR)/ \;
	@# ── Strip dtb.bin from rawprogram4.xml ──────────────────────────────────
	@# dtb.bin is a Yocto-built FAT32 image of kernel DTBs.  It is not publicly
	@# available and is not needed for UKI-based boot (DTB is embedded in uki.efi).
	@# Removing its entries prevents QDL from failing on a missing file.
	@sed -i '/filename="dtb\.bin"/d' $(BLOBS_DIR)/rawprogram4.xml
	@# ── DSP runtime (fastrpc_shell + skels) → rootfs overlay ────────────────
	@# Clone linux-msm/dsp-binaries at the pinned tag and install ONLY this
	@# board's files (via the repo's install.sh, which maps the versioned source
	@# dirs into dsp/{adsp,cdsp,...} and pulls licenses from WHENCE), plus the
	@# conf.d yamls that map the DT model -> DSP_LIBRARY_PATH.
	@if [ ! -d $(DSP_CLONE_DIR)/.git ]; then \
		echo "Cloning dsp-binaries ($(DSP_TAG))..."; \
		git clone --depth=1 --branch $(DSP_TAG) $(DSP_REPO) $(DSP_CLONE_DIR); \
	fi
	@mkdir -p $(DSP_SHARE_DIR)/conf.d
	@cd $(DSP_CLONE_DIR) && \
		grep '^Install:.*$(DSP_BOARD)' config.txt > .board-config.txt && \
		./scripts/install.sh .board-config.txt $(DSP_SHARE_DIR)
	@install -m 0644 $(DSP_CLONE_DIR)/conf.d/*.yaml $(DSP_SHARE_DIR)/conf.d/
	@echo "DSP runtime staged in $(DSP_SHARE_DIR)/ (board: $(DSP_BOARD))"
	@# Remoteproc/QUP firmware (qcom/qcm6490) is staged by the standalone
	@# 'linux-firmware' target (a prerequisite of buildroot), not here.
	@touch $(BLOBS_STAMP)
	@echo "Blobs ready in $(BLOBS_DIR)/"

fetch-blobs-clean:
	rm -rf $(BLOBS_DIR) $(OVERLAY_DIR)

################################################################################
# Yocto / kas — OE core-kit BSP image for rb3gen2
#
# Clones meta-qcom (if not already present), applies the local patches in
# kodiak/patches/meta-qcom/ (currently: add fastrpc-tests to the
# rb3gen2-core-kit image), and builds the Qualcomm BSP image via kas (meta-qcom
# BSP + OE no-distro build).
#
# Generates:
#   yocto/build/tmp/deploy/images/rb3gen2-core-kit/
#
# The deploy directory contains all files needed by the flash targets.  Copy
# them into kodiak/input/ so that flash-loader and flash-efi can find them:
#
#   cp $(YOCTO_DEPLOY)/{prog_firehose_ddr.elf,rawprogram*.xml,\
#      gpt_main0.bin,gpt_backup0.bin,patch0.xml} kodiak/input/
################################################################################
META_QCOM_DIR  ?= $(CURDIR)/yocto/meta-qcom
YOCTO_DEPLOY    = $(CURDIR)/yocto/build/tmp/deploy/images/rb3gen2-core-kit
YOCTO_FLASH     = $(YOCTO_DEPLOY)/core-image-base-rb3gen2-core-kit.rootfs.qcomflash

# Local meta-qcom patches (kodiak/patches/meta-qcom/*.patch) applied to the
# fresh clone before building. 0001 pulls the fastrpc recipe's -tests subpackage
# (fastrpc_test + DSP skels) into the rb3gen2-core-kit image so the FastRPC/PAS
# DSP path can be validated; it is not yet upstream, so we carry it here and
# apply it in the 'yocto' target.
META_QCOM_PATCH_DIR = $(CURDIR)/kodiak/patches/meta-qcom

.PHONY: yocto flash-yocto yocto-clean

yocto:
	@echo "WARNING: this build fetches and compiles a full Yocto stack."
	@echo "         It can take several hours depending on your machine and network."
	@echo "         For build issues consult: https://github.com/qualcomm-linux/meta-qcom/blob/main/README.md"
	@echo ""
	@if [ ! -d $(META_QCOM_DIR) ]; then \
		mkdir yocto; \
		git clone https://github.com/qualcomm-linux/meta-qcom $(META_QCOM_DIR); \
	fi
	@# Apply local meta-qcom patches not yet upstream (idempotent: skip if the
	@# change is already present, e.g. on an existing clone or after a re-run).
	@for p in $(sort $(wildcard $(META_QCOM_PATCH_DIR)/*.patch)); do \
		if git -C $(META_QCOM_DIR) apply --reverse --check "$$p" >/dev/null 2>&1; then \
			echo "Patch already applied: $$(basename $$p)"; \
		elif git -C $(META_QCOM_DIR) apply --check "$$p" >/dev/null 2>&1; then \
			echo "Applying $$(basename $$p) to meta-qcom..."; \
			git -C $(META_QCOM_DIR) apply "$$p"; \
		else \
			echo "ERROR: cannot apply $$(basename $$p) to $(META_QCOM_DIR)"; \
			echo "       (it neither applies cleanly nor is already present —"; \
			echo "        meta-qcom may have diverged; refresh the patch)"; \
			exit 1; \
		fi; \
	done
	KAS_BUILD_DIR=$(CURDIR)/yocto/build kas build yocto/meta-qcom/ci/rb3gen2-core-kit.yml
	mkdir -p $(CURDIR)/yocto/images
	ln -sfn $(YOCTO_FLASH) $(CURDIR)/yocto/images/rb3gen2-core-kit.qcomflash
	@echo ""
	@echo "Yocto build complete."
	@echo ""
	@echo "Flash artifacts are at:"
	@echo "  $(YOCTO_DEPLOY)"
	@echo ""
	@echo "Copy them to kodiak/input/ before running flash-loader or flash-efi:"
	@echo "  cp \$(YOCTO_DEPLOY)/{prog_firehose_ddr.elf,rawprogram*.xml,gpt_main0.bin,gpt_backup0.bin,patch0.xml} \$(CURDIR)/kodiak/input/"
	@echo ""

# flash-yocto — Flash the complete, unmodified Yocto release image.
#
# Programs the pristine $(YOCTO_FLASH) qcomflash directory as-is — bootloader,
# firmware, efi.bin and rootfs.img — to verify the default hardware against the
# released BSP.  No local build artifacts are substituted.  Every rawprogram /
# patch XML the release ships is programmed (RB3 Gen2 uses LUNs 0,1,2,4), so the
# set adapts to whatever is present in the deploy directory.
#
# NOTE: this overwrites whatever 'make flash-loader' / 'make flash-efi'
# installed.  Re-run those afterward to restore your custom build.
flash-yocto:
	@if [ ! -f "$(YOCTO_FLASH)/prog_firehose_ddr.elf" ]; then \
		echo "ERROR: Yocto flash image not found at $(YOCTO_FLASH)"; \
		echo "       Run 'make yocto' first to build the release image."; \
		exit 1; \
	fi
	cd $(YOCTO_FLASH) && \
		qdl --debug prog_firehose_ddr.elf rawprogram*.xml patch*.xml

yocto-clean:
	rm -rf $(META_QCOM_DIR)
